# Importing

In [3]:
import numpy as np
import pandas as pd

# Reading CSVs

In [4]:
# movies.csv
url = 'https://drive.google.com/file/d/1EknR8ceW4HEkjW-41F4z_IVku0RZERWH/view?usp=sharing' 
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
movies = pd.read_csv(path)

# links.csv
url = 'https://drive.google.com/file/d/1F0jEbRxpqt1L6B_OjiLK29wZtj5JIocV/view?usp=sharing' 
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
links = pd.read_csv(path)

# 'ratings.csv'
url = 'https://drive.google.com/file/d/1IdcUbfqlIIY0djoAtTKEDXhL6TCXyCoG/view?usp=sharing' 
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
ratings = pd.read_csv(path) 

# tags.csv
url = 'https://drive.google.com/file/d/1kOIkbYH6xjM_38EKqienvHtzmWUGunt4/view?usp=sharing' 
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
tags = pd.read_csv(path)

In [5]:
tags.columns

Index(['userId ', 'movieId ',
       'tag                                                                                   ',
       'timestamp'],
      dtype='object')

In [6]:
movies.head(3)

,movieId,title,genres
0,1,Toy Story (1995) ...,Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995) ...,Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995) ...,Comedy|Romance

In the `geodata` dataset we have info about the places. We will only use the `name` column.

In [7]:
ratings.head(2)

   userId   movieId   rating   timestamp
0        1         1      4.0  964982703
1        1         3      4.0  964981247

In [8]:
ratings.columns

Index(['userId ', 'movieId ', 'rating ', 'timestamp'], dtype='object')

In [9]:
Ratings = ratings.rename({'userId ': 'userId', 'movieId ': 'movieId', 'rating ':'rating'}, axis=1)

In [10]:
Ratings.columns

Index(['userId', 'movieId', 'rating', 'timestamp'], dtype='object')

In [11]:
Ratings

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

## Renaming columns of Movies df

In [12]:
movies.columns

Index(['movieId ',
       'title                                                                                                                                                          ',
       'genres'],
      dtype='object')

In [13]:
Movies = movies.rename({'movieId ': 'movieId', 'title                                                                                                                                                          ':'title'
, 'genres' :'genres'}, axis=1)

In [14]:
Movies.columns

Index(['movieId', 'title', 'genres'], dtype='object')

In [15]:
tags.head()

,userId,movieId,tag,timestamp
0,2,60756,funny ...,1445714994
1,2,60756,Highly quotable ...,1445714996
2,2,60756,will ferrell ...,1445714992
3,2,89774,Boxing story ...,1445715207
4,2,89774,MMA ...,1445715200

In [16]:
links.head()

   movieId   imdbId     tmdbId
0         1    114709    862.0
1         2    113497   8844.0
2         3    113228  15602.0
3         4    114885  31357.0
4         5    113041  11862.0

# Merging Movies and Ratings

In [17]:
Ratings_Movies = Ratings.merge(Movies, on='movieId')

In [18]:
Ratings_Movies

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995) ...,Adventure|Animation|Children|Comedy|Fantasy
1,5,1,4.0,847434962,Toy Story (1995) ...,Adventure|Animation|Children|Comedy|Fantasy
2,7,1,4.5,1106635946,Toy Story (1995) ...,Adventure|Animation|Children|Comedy|Fantasy
3,15,1,2.5,1510577970,Toy Story (1995) ...,Adventure|Animation|Children|Comedy|Fantasy
4,17,1,4.5,1305696483,Toy Story (1995) ...,Adventure|Animation|Children|Comedy|Fantasy
...,...,...,...,...,...,...
100831,610,160341,2.5,1479545749,Bloodmoon (1997) ...,Action|Thriller
100832,610,160527,4.5,1479544998,Sympathy for the Underdog (1971) ...,Action|Crime|Drama
100833,610,160836,3.0,1493844794,Hazard (2005) ...,Action|Drama|Thriller
100834,610,163937,3.5,1493848789,Blair Witch (2016) ...,Horror|Thriller
100835,610,163981,3.5,1493850155,31 (2016) ...,Horror

# Dropping Movie Ids with only one Rating

In [19]:
Ratings_drop = Ratings_Movies["movieId"].value_counts()

In [20]:
to_remove = Ratings_drop[Ratings_drop <= 10].index

In [21]:
Ratings_Movies_new = Ratings_Movies[~Ratings_Movies.movieId.isin(to_remove)]

In [22]:
Ratings_Movies_new.movieId.value_counts()

356      329
318      317
296      307
593      279
2571     278
        ...
2822      11
66203     11
5294      11
5650      11
5128      11
Name: movieId, Length: 2121, dtype: int64

In [23]:
Ratings_Movies_new = Ratings_Movies_new.drop(columns = "timestamp")

In [24]:
Ratings_Movies_new

,userId,movieId,rating,title,genres
0,1,1,4.0,Toy Story (1995) ...,Adventure|Animation|Children|Comedy|Fantasy
1,5,1,4.0,Toy Story (1995) ...,Adventure|Animation|Children|Comedy|Fantasy
2,7,1,4.5,Toy Story (1995) ...,Adventure|Animation|Children|Comedy|Fantasy
3,15,1,2.5,Toy Story (1995) ...,Adventure|Animation|Children|Comedy|Fantasy
4,17,1,4.5,Toy Story (1995) ...,Adventure|Animation|Children|Comedy|Fantasy
...,...,...,...,...,...
96230,558,5128,1.0,Queen of the Damned (2002) ...,Fantasy|Horror
96231,599,5128,2.5,Queen of the Damned (2002) ...,Fantasy|Horror
96232,600,5128,2.5,Queen of the Damned (2002) ...,Fantasy|Horror
96233,605,5128,3.0,Queen of the Damned (2002) ...,Fantasy|Horror
96234,610,5128,2.0,Queen of the Damned (2002) ...,Fantasy|Horror

In [25]:
Test_df = Ratings_Movies_new.groupby(["movieId"]).userId.count()
Test_df

movieId
1         215
2         110
3          52
5          49
6         102
         ...
174055     13
176371     18
177765     13
179819     12
187593     12
Name: userId, Length: 2121, dtype: int64

In [26]:
Test_df = pd.DataFrame(Test_df)

In [27]:
Test_df["average_rating"] = Ratings_Movies_new.groupby(["movieId"]).rating.mean()

In [28]:
popular_movies = Test_df.merge(Movies, on='movieId')

In [29]:
popular_movies.columns

Index(['movieId', 'userId', 'average_rating', 'title', 'genres'], dtype='object')

In [30]:
popular_movies

,movieId,userId,average_rating,title,genres
0,1,215,3.920930,Toy Story (1995) ...,Adventure|Animation|Children|Comedy|Fantasy
1,2,110,3.431818,Jumanji (1995) ...,Adventure|Children|Fantasy
2,3,52,3.259615,Grumpier Old Men (1995) ...,Comedy|Romance
3,5,49,3.071429,Father of the Bride Part II (1995) ...,Comedy
4,6,102,3.946078,Heat (1995) ...,Action|Crime|Thriller
...,...,...,...,...,...
2116,174055,13,3.423077,Dunkirk (2017) ...,Action|Drama|Thriller|War
2117,176371,18,3.805556,Blade Runner 2049 (2017) ...,Sci-Fi
2118,177765,13,3.538462,Coco (2017) ...,Adventure|Animation|Children
2119,179819,12,3.125000,Star Wars: The Last Jedi (2017) ...,Action|Adventure|Fantasy|Sci-Fi
2120,187593,12,3.875000,Deadpool 2 (2018) ...,Action|Comedy|Sci-Fi

# Score

In [31]:
popular_movies['title'].str.strip()

0                         Toy Story (1995)
1                           Jumanji (1995)
2                  Grumpier Old Men (1995)
3       Father of the Bride Part II (1995)
4                              Heat (1995)
                       ...
2116                        Dunkirk (2017)
2117              Blade Runner 2049 (2017)
2118                           Coco (2017)
2119       Star Wars: The Last Jedi (2017)
2120                     Deadpool 2 (2018)
Name: title, Length: 2121, dtype: object

In [32]:
popular_movies.title

0       Toy Story (1995)                              ...
1       Jumanji (1995)                                ...
2       Grumpier Old Men (1995)                       ...
3       Father of the Bride Part II (1995)            ...
4       Heat (1995)                                   ...
                              ...
2116    Dunkirk (2017)                                ...
2117    Blade Runner 2049 (2017)                      ...
2118    Coco (2017)                                   ...
2119    Star Wars: The Last Jedi (2017)               ...
2120    Deadpool 2 (2018)                             ...
Name: title, Length: 2121, dtype: object

In [33]:
popular_movies["score"] = round(popular_movies["userId"]*popular_movies["average_rating"] / (popular_movies["userId"] + popular_movies["average_rating"] ),2)

# Creating a Function

In [36]:
popular_movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2121 entries, 0 to 2120
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   movieId         2121 non-null   int64
 1   userId          2121 non-null   int64
 2   average_rating  2121 non-null   float64
 3   title           2121 non-null   object
 4   genres          2121 non-null   object
 5   score           2121 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 116.0+ KB

In [45]:
popular_movies.set_index("title", inplace = True)

In [42]:
popular_movies

,movieId,userId,average_rating,title,genres,score,Sorted_Score
0,1,215,3.920930,Toy Story (1995) ...,Adventure|Animation|Children|Comedy|Fantasy,3.85,3.85
1,2,110,3.431818,Jumanji (1995) ...,Adventure|Children|Fantasy,3.33,3.33
2,3,52,3.259615,Grumpier Old Men (1995) ...,Comedy|Romance,3.07,3.07
3,5,49,3.071429,Father of the Bride Part II (1995) ...,Comedy,2.89,2.89
4,6,102,3.946078,Heat (1995) ...,Action|Crime|Thriller,3.80,3.80
...,...,...,...,...,...,...,...
2116,174055,13,3.423077,Dunkirk (2017) ...,Action|Drama|Thriller|War,2.71,2.71
2117,176371,18,3.805556,Blade Runner 2049 (2017) ...,Sci-Fi,3.14,3.14
2118,177765,13,3.538462,Coco (2017) ...,Adventure|Animation|Children,2.78,2.78
2119,179819,12,3.125000,Star Wars: The Last Jedi (2017) ...,Action|Adventure|Fantasy|Sci-Fi,2.48,2.48
2120,187593,12,3.875000,Deadpool 2 (2018) ...,Action|Comedy|Sci-Fi,2.93,2.93

In [46]:
def popular_movie_list(N):
  return popular_movies.score.sort_values(ascending = False).head(N).index

In [47]:
popular_movie_list(10)

Index(['Shawshank Redemption, The (1994)                                                                                                                             ',
       'Godfather, The (1972)                                                                                                                                        ',
       'Fight Club (1999)                                                                                                                                              ',
       'Star Wars: Episode IV - A New Hope (1977)                                                                                                                      ',
       'Schindler's List (1993)                                                                                                                                        ',
       'Usual Suspects, The (1995)                                                                                                                                   ',
       'Pulp Fiction (1994)                                                                                                                                            ',
       'Matrix, The (1999)                                                                                                                                           ',
       'Star Wars: Episode V - The Empire Strikes Back (1980)                                                                                                          ',
       'Godfather: Part II, The (1974)                                                                                                                               '],
      dtype='object', name='title')